rds_instance_id: database
s3_bucket: some-bucket
s3_prefix: sql-dump

aws_access_key_id: COMPLETELYRANDOM
aws_secret_access_key: completelyrandom
aws_region: us-east-1

db:
  type: mysql
  database: db
  username: user
  password: password

dump_directory: /tmp/sql-dump/
