rds_instance_id: database
rds_subnet_group: default
s3_bucket: some-bucket
s3_prefix: sql-dump

aws_access_key_id: COMPLETELYRANDOM
aws_secret_access_key: completelyrandom
aws_region: us-east-1

db_data: db
db_user: user
db_password: password
compress_command: gzip
