rds_instance_id: database
rds_subnet_group: default
s3_bucket: some-bucket
s3_prefix: sql-dump

aws_access_key_id: COMPLETELYRANDOM
aws_secret_access_key: completelyrandom
aws_region: us-east-1

databases:
  - name: db1
    user: user1
    password: password1
  - name: db2
    user: user2
    password: password2

compress_command: gzip
